-- 0001 — Initial schema for the personal 60-day fitness tracker.
--
-- Design notes
-- * The programme definition (exercises, sets, reps, supersets) lives in the frontend
--   (src/data/workout-data.ts). The database stores user state only.
-- * Every user-owned table carries user_id. Child tables reference their parent with a
--   COMPOSITE foreign key (parent_id, user_id) -> parent(id, user_id). Combined with RLS
--   (user_id = auth.uid()), a user cannot attach rows to someone else's parent row, even
--   by guessing a UUID.
-- * Weights on exercise sets are stored in kilograms (weight_kg). Unit is a display preference.

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Exercise codes (lookup). Rejects unknown exercise codes at the database level.
-- Must stay in sync with src/data/workout-data.ts (tests/programme.test.ts checks it).
-- ---------------------------------------------------------------------------
create table public.exercise_codes (
  code text primary key check (code ~ '^[a-z0-9_]{2,64}$')
);

insert into public.exercise_codes (code) values
  ('barbell_bentover_row'), ('barbell_clean_and_press'), ('bench_press'), ('cable_crossover'),
  ('cable_shrug'), ('close_grip_bench_press'), ('db_incline_press'), ('db_kickback'),
  ('db_lateral_raise'), ('db_overhead_extension'), ('db_rear_delt_flye'), ('db_shrug'),
  ('db_spider_curl'), ('db_upright_row'), ('deadlift'), ('flat_db_press'),
  ('incline_db_flye'), ('incline_db_press'), ('incline_french_press'), ('lat_pulldown'),
  ('leg_curl'), ('leg_extension'), ('leg_press'), ('low_cable_pull'),
  ('pullup'), ('pushup'), ('reverse_curl'), ('rope_high_pull'),
  ('rope_pushdown'), ('scott_press'), ('seated_calf_raise'), ('seated_db_curl'),
  ('single_arm_db_overhead_press'), ('single_arm_db_row'), ('squat'), ('standing_calf_raise'),
  ('standing_single_arm_cable_row'), ('standing_straight_bar_cable_curl'), ('straight_arm_pushdown'),
  ('straight_bar_curl'), ('walking_lunge');

-- ---------------------------------------------------------------------------
-- Profiles (1:1 with auth.users). Passwords live in Supabase Auth, never here.
-- ---------------------------------------------------------------------------
create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) <= 80),
  weight_unit  text not null default 'kg' check (weight_unit in ('kg', 'lb')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

-- Create a profile row automatically when someone signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id) values (new.id) on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Programmes. A user can have many over time; at most one is active.
-- ---------------------------------------------------------------------------
create table public.programmes (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  name       text not null default '60 Days to Fit' check (char_length(name) between 1 and 120),
  start_date date not null,
  status     text not null default 'active' check (status in ('active', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id)
);

create unique index programmes_one_active_per_user on public.programmes (user_id) where status = 'active';

create trigger programmes_updated_at before update on public.programmes
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Programme days. 60 rows per programme, generated by the app from the source schedule.
-- ---------------------------------------------------------------------------
create table public.programme_days (
  id             uuid primary key default gen_random_uuid(),
  programme_id   uuid not null,
  user_id        uuid not null default auth.uid(),
  day_number     integer not null check (day_number between 1 and 60),
  cycle_number   integer not null check (cycle_number between 1 and 5),
  workout_code   text check (workout_code in ('A', 'B', 'C', 'D')),
  workout_type   text check (workout_type in ('light', 'heavy')),
  is_rest_day    boolean not null,
  scheduled_date date not null,
  completed      boolean not null default false,
  completed_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  foreign key (programme_id, user_id) references public.programmes (id, user_id) on delete cascade,
  unique (programme_id, day_number),
  unique (id, user_id),
  -- Structural integrity of the 12-day cycle (days 3, 6, 9, 12 of each cycle are rest).
  constraint programme_days_cycle_matches_day check (cycle_number = ((day_number - 1) / 12) + 1),
  constraint programme_days_rest_pattern check (is_rest_day = (((day_number - 1) % 12) in (2, 5, 8, 11))),
  constraint programme_days_rest_has_no_workout check (
    (is_rest_day and workout_code is null and workout_type is null)
    or (not is_rest_day and workout_code is not null and workout_type is not null)
  ),
  constraint programme_days_completed_at check (completed or completed_at is null)
);

create trigger programme_days_updated_at before update on public.programme_days
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Workout sessions. The actual workout log for a programme day (one per day in v1).
-- ---------------------------------------------------------------------------
create table public.workout_sessions (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null default auth.uid(),
  programme_day_id uuid not null,
  started_at       timestamptz,
  completed_at     timestamptz,
  notes            text check (char_length(notes) <= 2000),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  foreign key (programme_day_id, user_id) references public.programme_days (id, user_id) on delete cascade,
  unique (programme_day_id),
  unique (id, user_id)
);

create trigger workout_sessions_updated_at before update on public.workout_sessions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Exercise sets.
-- ---------------------------------------------------------------------------
create table public.exercise_sets (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null default auth.uid(),
  workout_session_id uuid not null,
  exercise_code      text not null references public.exercise_codes (code),
  set_number         integer not null check (set_number between 1 and 5),
  weight_kg          numeric(7, 3) check (weight_kg >= 0 and weight_kg <= 1000),
  reps               integer check (reps between 0 and 200),
  notes              text check (char_length(notes) <= 500),
  completed          boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  foreign key (workout_session_id, user_id) references public.workout_sessions (id, user_id) on delete cascade,
  unique (workout_session_id, exercise_code, set_number)
);

create trigger exercise_sets_updated_at before update on public.exercise_sets
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Per-exercise notes within a session.
-- ---------------------------------------------------------------------------
create table public.exercise_notes (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null default auth.uid(),
  workout_session_id uuid not null,
  exercise_code      text not null references public.exercise_codes (code),
  notes              text not null check (char_length(notes) <= 2000),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  foreign key (workout_session_id, user_id) references public.workout_sessions (id, user_id) on delete cascade,
  unique (workout_session_id, exercise_code)
);

create trigger exercise_notes_updated_at before update on public.exercise_notes
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Body weight. One entry per user per date.
-- ---------------------------------------------------------------------------
create table public.body_weight_entries (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  recorded_at date not null,
  weight      numeric(7, 3) not null check (weight > 0 and weight <= 1100),
  unit        text not null check (unit in ('kg', 'lb')),
  notes       text check (char_length(notes) <= 500),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, recorded_at)
);

create trigger body_weight_entries_updated_at before update on public.body_weight_entries
  for each row execute function public.set_updated_at();
