-- 0004 — Programs, program runs and dated training sessions.
--
-- The app moves from "one fixed 60-day calendar" to:
--   custom_programs   — user-made programs (e.g. Push/Pull/Legs), stored as validated JSON
--   programmes        — now a program RUN (which program, start date, status)
--   run_days          — which days of a run are done / skipped, and on what date
--   training_sessions — what was trained on a date (a program day, a swapped workout, or a free workout)
--   session_sets / session_notes — the logged sets and per-exercise notes
--
-- Existing data in programme_days / workout_sessions / exercise_sets / exercise_notes is copied
-- across below. The old tables are left in place (unused by the app) so nothing is lost; they can
-- be dropped in a later migration.

-- ---------------------------------------------------------------------------
-- Custom programs
-- ---------------------------------------------------------------------------
create table public.custom_programs (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  name       text not null check (char_length(name) between 1 and 80),
  definition jsonb not null check (jsonb_typeof(definition) = 'object' and pg_column_size(definition) < 65536),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger custom_programs_updated_at before update on public.custom_programs
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- programmes → program runs
-- ---------------------------------------------------------------------------
alter table public.programmes
  add column program_ref text not null default 'builtin:60days'
    check (program_ref ~ '^(builtin:[a-z0-9_-]{1,40}|custom:[0-9a-f-]{36})$'),
  add column ended_at timestamptz;

-- ---------------------------------------------------------------------------
-- Run days (done / skipped, with the date it happened)
-- ---------------------------------------------------------------------------
create table public.run_days (
  id           uuid primary key default gen_random_uuid(),
  programme_id uuid not null,
  user_id      uuid not null default auth.uid(),
  day_number   integer not null check (day_number between 1 and 1000),
  status       text not null check (status in ('done', 'skipped')),
  occurred_on  date not null,
  -- Soft link to the session that completed the day (sessions and run days sync independently).
  session_id   uuid,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  foreign key (programme_id, user_id) references public.programmes (id, user_id) on delete cascade,
  unique (programme_id, day_number)
);

create trigger run_days_updated_at before update on public.run_days
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Training sessions (ids are generated by the app so offline edits can be synced later)
-- ---------------------------------------------------------------------------
create table public.training_sessions (
  id           uuid primary key,
  user_id      uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  programme_id uuid,
  day_number   integer check (day_number between 1 and 1000),
  workout_key  text check (char_length(workout_key) <= 40),
  title        text not null check (char_length(title) between 1 and 80),
  session_date date not null,
  status       text not null default 'in_progress' check (status in ('in_progress', 'done')),
  completed_at timestamptz,
  plan         jsonb not null default '[]'::jsonb check (jsonb_typeof(plan) = 'array' and pg_column_size(plan) < 65536),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  -- A session belongs to one of the user's own runs, or to none (free workout).
  foreign key (programme_id, user_id) references public.programmes (id, user_id) on delete cascade,
  unique (id, user_id),
  constraint training_sessions_run_day check ((programme_id is null) = (day_number is null))
);

create trigger training_sessions_updated_at before update on public.training_sessions
  for each row execute function public.set_updated_at();

create table public.session_sets (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid(),
  session_id    uuid not null,
  exercise_code text not null check (exercise_code ~ '^[a-z0-9_]{2,64}$'),
  set_number    integer not null check (set_number between 1 and 10),
  weight_kg     numeric(7, 3) check (weight_kg >= 0 and weight_kg <= 1000),
  reps          integer check (reps between 0 and 200),
  completed     boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  foreign key (session_id, user_id) references public.training_sessions (id, user_id) on delete cascade,
  unique (session_id, exercise_code, set_number)
);

create trigger session_sets_updated_at before update on public.session_sets
  for each row execute function public.set_updated_at();

create table public.session_notes (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid(),
  session_id    uuid not null,
  exercise_code text not null check (exercise_code ~ '^[a-z0-9_]{2,64}$'),
  notes         text not null check (char_length(notes) <= 2000),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  foreign key (session_id, user_id) references public.training_sessions (id, user_id) on delete cascade,
  unique (session_id, exercise_code)
);

create trigger session_notes_updated_at before update on public.session_notes
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security (same rule as 0002: only your own rows; anon gets nothing)
-- ---------------------------------------------------------------------------
alter table public.custom_programs   enable row level security;
alter table public.run_days          enable row level security;
alter table public.training_sessions enable row level security;
alter table public.session_sets      enable row level security;
alter table public.session_notes     enable row level security;

revoke all on public.custom_programs, public.run_days, public.training_sessions, public.session_sets, public.session_notes from anon;

create policy "custom_programs: own rows" on public.custom_programs for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "run_days: own rows" on public.run_days for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "training_sessions: own rows" on public.training_sessions for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "session_sets: own rows" on public.session_sets for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "session_notes: own rows" on public.session_notes for all to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
create index custom_programs_user_idx          on public.custom_programs (user_id);
create index run_days_user_idx                 on public.run_days (user_id);
create index training_sessions_user_date_idx   on public.training_sessions (user_id, session_date);
create index training_sessions_run_day_idx     on public.training_sessions (programme_id, day_number);
create index session_sets_user_exercise_idx    on public.session_sets (user_id, exercise_code);
create index session_notes_user_idx            on public.session_notes (user_id);

-- ---------------------------------------------------------------------------
-- Copy existing data into the new tables
-- ---------------------------------------------------------------------------
insert into public.training_sessions
  (id, user_id, programme_id, day_number, workout_key, title, session_date, status, completed_at, created_at, updated_at)
select ws.id, ws.user_id, pd.programme_id, pd.day_number,
       pd.workout_code || '-' || pd.workout_type,
       case pd.workout_code when 'A' then 'Shoulders / Traps' when 'B' then 'Back / Biceps / Forearms'
                            when 'C' then 'Chest / Triceps' else 'Legs' end,
       coalesce(pd.completed_at::date, pd.scheduled_date),
       case when pd.completed then 'done' else 'in_progress' end,
       pd.completed_at, ws.created_at, ws.updated_at
from public.workout_sessions ws
join public.programme_days pd on pd.id = ws.programme_day_id
where not pd.is_rest_day;

insert into public.session_sets (user_id, session_id, exercise_code, set_number, weight_kg, reps, completed)
select es.user_id, es.workout_session_id, es.exercise_code, es.set_number, es.weight_kg, es.reps, es.completed
from public.exercise_sets es
where exists (select 1 from public.training_sessions t where t.id = es.workout_session_id);

insert into public.session_notes (user_id, session_id, exercise_code, notes)
select en.user_id, en.workout_session_id, en.exercise_code, en.notes
from public.exercise_notes en
where exists (select 1 from public.training_sessions t where t.id = en.workout_session_id);

insert into public.run_days (programme_id, user_id, day_number, status, occurred_on, session_id)
select pd.programme_id, pd.user_id, pd.day_number, 'done', coalesce(pd.completed_at::date, pd.scheduled_date),
       (select ws.id from public.workout_sessions ws where ws.programme_day_id = pd.id and not pd.is_rest_day)
from public.programme_days pd
where pd.completed;
